


using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Data;
using System.Data.SqlClient;
using UHub.CoreLib.RegExp.Compiled;


//FILE GENERATED BY A TOOL
namespace UHub.CoreLib.RegExp.Compiled
{

    public static class RgxCompiled
    {


        public static partial class Config
        {
            public static UHub.CoreLib.RegExp.Compiler.Output.Config.INTERNAL_URL INTERNAL_URL = new UHub.CoreLib.RegExp.Compiler.Output.Config.INTERNAL_URL();
        }


        public static partial class Config
        {
            public static UHub.CoreLib.RegExp.Compiler.Output.Config.INTERNAL_URL_B INTERNAL_URL_B = new UHub.CoreLib.RegExp.Compiler.Output.Config.INTERNAL_URL_B();
        }


        public static partial class Cookie
        {
            public static UHub.CoreLib.RegExp.Compiler.Output.Cookie.DOMAIN DOMAIN = new UHub.CoreLib.RegExp.Compiler.Output.Cookie.DOMAIN();
        }


        public static partial class DataInterop
        {
            public static UHub.CoreLib.RegExp.Compiler.Output.DataInterop.INVALID_ARGUMENT INVALID_ARGUMENT = new UHub.CoreLib.RegExp.Compiler.Output.DataInterop.INVALID_ARGUMENT();
        }


        public static partial class DataInterop
        {
            public static UHub.CoreLib.RegExp.Compiler.Output.DataInterop.INVALID_ARGUMENT_B INVALID_ARGUMENT_B = new UHub.CoreLib.RegExp.Compiler.Output.DataInterop.INVALID_ARGUMENT_B();
        }


        public static partial class EntComment
        {
            public static UHub.CoreLib.RegExp.Compiler.Output.EntComment.CONTENT CONTENT = new UHub.CoreLib.RegExp.Compiler.Output.EntComment.CONTENT();
        }


        public static partial class EntComment
        {
            public static UHub.CoreLib.RegExp.Compiler.Output.EntComment.CONTENT_B CONTENT_B = new UHub.CoreLib.RegExp.Compiler.Output.EntComment.CONTENT_B();
        }


        public static partial class Entity
        {
            public static UHub.CoreLib.RegExp.Compiler.Output.Entity.ENT_NAME ENT_NAME = new UHub.CoreLib.RegExp.Compiler.Output.Entity.ENT_NAME();
        }


        public static partial class Entity
        {
            public static UHub.CoreLib.RegExp.Compiler.Output.Entity.ENT_NAME_B ENT_NAME_B = new UHub.CoreLib.RegExp.Compiler.Output.Entity.ENT_NAME_B();
        }


        public static partial class EntPost
        {
            public static UHub.CoreLib.RegExp.Compiler.Output.EntPost.NAME NAME = new UHub.CoreLib.RegExp.Compiler.Output.EntPost.NAME();
        }


        public static partial class EntPost
        {
            public static UHub.CoreLib.RegExp.Compiler.Output.EntPost.NAME_B NAME_B = new UHub.CoreLib.RegExp.Compiler.Output.EntPost.NAME_B();
        }


        public static partial class EntPost
        {
            public static UHub.CoreLib.RegExp.Compiler.Output.EntPost.CONTENT CONTENT = new UHub.CoreLib.RegExp.Compiler.Output.EntPost.CONTENT();
        }


        public static partial class EntPost
        {
            public static UHub.CoreLib.RegExp.Compiler.Output.EntPost.CONTENT_B CONTENT_B = new UHub.CoreLib.RegExp.Compiler.Output.EntPost.CONTENT_B();
        }


        public static partial class EntSchoolClub
        {
            public static UHub.CoreLib.RegExp.Compiler.Output.EntSchoolClub.NAME NAME = new UHub.CoreLib.RegExp.Compiler.Output.EntSchoolClub.NAME();
        }


        public static partial class EntSchoolClub
        {
            public static UHub.CoreLib.RegExp.Compiler.Output.EntSchoolClub.NAME_B NAME_B = new UHub.CoreLib.RegExp.Compiler.Output.EntSchoolClub.NAME_B();
        }


        public static partial class EntSchoolClub
        {
            public static UHub.CoreLib.RegExp.Compiler.Output.EntSchoolClub.DESCRIPTION DESCRIPTION = new UHub.CoreLib.RegExp.Compiler.Output.EntSchoolClub.DESCRIPTION();
        }


        public static partial class EntSchoolClub
        {
            public static UHub.CoreLib.RegExp.Compiler.Output.EntSchoolClub.DESCRIPTION_B DESCRIPTION_B = new UHub.CoreLib.RegExp.Compiler.Output.EntSchoolClub.DESCRIPTION_B();
        }


        public static partial class EntUser
        {
            public static UHub.CoreLib.RegExp.Compiler.Output.EntUser.USERNAME USERNAME = new UHub.CoreLib.RegExp.Compiler.Output.EntUser.USERNAME();
        }


        public static partial class EntUser
        {
            public static UHub.CoreLib.RegExp.Compiler.Output.EntUser.USERNAME_B USERNAME_B = new UHub.CoreLib.RegExp.Compiler.Output.EntUser.USERNAME_B();
        }


        public static partial class EntUser
        {
            public static UHub.CoreLib.RegExp.Compiler.Output.EntUser.PASSWORD PASSWORD = new UHub.CoreLib.RegExp.Compiler.Output.EntUser.PASSWORD();
        }


        public static partial class EntUser
        {
            public static UHub.CoreLib.RegExp.Compiler.Output.EntUser.PASSWORD_B PASSWORD_B = new UHub.CoreLib.RegExp.Compiler.Output.EntUser.PASSWORD_B();
        }


        public static partial class EntUser
        {
            public static UHub.CoreLib.RegExp.Compiler.Output.EntUser.EMAIL EMAIL = new UHub.CoreLib.RegExp.Compiler.Output.EntUser.EMAIL();
        }


        public static partial class EntUser
        {
            public static UHub.CoreLib.RegExp.Compiler.Output.EntUser.EMAIL_B EMAIL_B = new UHub.CoreLib.RegExp.Compiler.Output.EntUser.EMAIL_B();
        }


        public static partial class EntUser
        {
            public static UHub.CoreLib.RegExp.Compiler.Output.EntUser.EMAIL_DOMAIN EMAIL_DOMAIN = new UHub.CoreLib.RegExp.Compiler.Output.EntUser.EMAIL_DOMAIN();
        }


        public static partial class EntUser
        {
            public static UHub.CoreLib.RegExp.Compiler.Output.EntUser.EMAIL_DOMAIN_B EMAIL_DOMAIN_B = new UHub.CoreLib.RegExp.Compiler.Output.EntUser.EMAIL_DOMAIN_B();
        }


        public static partial class EntUser
        {
            public static UHub.CoreLib.RegExp.Compiler.Output.EntUser.NAME NAME = new UHub.CoreLib.RegExp.Compiler.Output.EntUser.NAME();
        }


        public static partial class EntUser
        {
            public static UHub.CoreLib.RegExp.Compiler.Output.EntUser.NAME_B NAME_B = new UHub.CoreLib.RegExp.Compiler.Output.EntUser.NAME_B();
        }


        public static partial class EntUser
        {
            public static UHub.CoreLib.RegExp.Compiler.Output.EntUser.REF_UID REF_UID = new UHub.CoreLib.RegExp.Compiler.Output.EntUser.REF_UID();
        }


        public static partial class EntUser
        {
            public static UHub.CoreLib.RegExp.Compiler.Output.EntUser.REF_UID_B REF_UID_B = new UHub.CoreLib.RegExp.Compiler.Output.EntUser.REF_UID_B();
        }


        public static partial class EntUser
        {
            public static UHub.CoreLib.RegExp.Compiler.Output.EntUser.PHONE PHONE = new UHub.CoreLib.RegExp.Compiler.Output.EntUser.PHONE();
        }


        public static partial class EntUser
        {
            public static UHub.CoreLib.RegExp.Compiler.Output.EntUser.PHONE_B PHONE_B = new UHub.CoreLib.RegExp.Compiler.Output.EntUser.PHONE_B();
        }


        public static partial class EntUser
        {
            public static UHub.CoreLib.RegExp.Compiler.Output.EntUser.MAJOR MAJOR = new UHub.CoreLib.RegExp.Compiler.Output.EntUser.MAJOR();
        }


        public static partial class EntUser
        {
            public static UHub.CoreLib.RegExp.Compiler.Output.EntUser.MAJOR_B MAJOR_B = new UHub.CoreLib.RegExp.Compiler.Output.EntUser.MAJOR_B();
        }


        public static partial class EntUser
        {
            public static UHub.CoreLib.RegExp.Compiler.Output.EntUser.YEAR YEAR = new UHub.CoreLib.RegExp.Compiler.Output.EntUser.YEAR();
        }


        public static partial class EntUser
        {
            public static UHub.CoreLib.RegExp.Compiler.Output.EntUser.YEAR_B YEAR_B = new UHub.CoreLib.RegExp.Compiler.Output.EntUser.YEAR_B();
        }


        public static partial class EntUser
        {
            public static UHub.CoreLib.RegExp.Compiler.Output.EntUser.GRADE_DATE GRADE_DATE = new UHub.CoreLib.RegExp.Compiler.Output.EntUser.GRADE_DATE();
        }


        public static partial class EntUser
        {
            public static UHub.CoreLib.RegExp.Compiler.Output.EntUser.GRAD_DATE_B GRAD_DATE_B = new UHub.CoreLib.RegExp.Compiler.Output.EntUser.GRAD_DATE_B();
        }


        public static partial class EntUser
        {
            public static UHub.CoreLib.RegExp.Compiler.Output.EntUser.COMPANY COMPANY = new UHub.CoreLib.RegExp.Compiler.Output.EntUser.COMPANY();
        }


        public static partial class EntUser
        {
            public static UHub.CoreLib.RegExp.Compiler.Output.EntUser.COMPANY_B COMPANY_B = new UHub.CoreLib.RegExp.Compiler.Output.EntUser.COMPANY_B();
        }


        public static partial class EntUser
        {
            public static UHub.CoreLib.RegExp.Compiler.Output.EntUser.JOB_TITLE JOB_TITLE = new UHub.CoreLib.RegExp.Compiler.Output.EntUser.JOB_TITLE();
        }


        public static partial class EntUser
        {
            public static UHub.CoreLib.RegExp.Compiler.Output.EntUser.JOB_TITLE_B JOB_TITLE_B = new UHub.CoreLib.RegExp.Compiler.Output.EntUser.JOB_TITLE_B();
        }


        public static partial class FileUpload
        {
            public static UHub.CoreLib.RegExp.Compiler.Output.FileUpload.CHUNK_ID CHUNK_ID = new UHub.CoreLib.RegExp.Compiler.Output.FileUpload.CHUNK_ID();
        }


        public static partial class FileUpload
        {
            public static UHub.CoreLib.RegExp.Compiler.Output.FileUpload.CHUNK_ID_B CHUNK_ID_B = new UHub.CoreLib.RegExp.Compiler.Output.FileUpload.CHUNK_ID_B();
        }


        public static partial class FileUpload
        {
            public static UHub.CoreLib.RegExp.Compiler.Output.FileUpload.FILE_NAME FILE_NAME = new UHub.CoreLib.RegExp.Compiler.Output.FileUpload.FILE_NAME();
        }


        public static partial class FileUpload
        {
            public static UHub.CoreLib.RegExp.Compiler.Output.FileUpload.FILE_NAME_B FILE_NAME_B = new UHub.CoreLib.RegExp.Compiler.Output.FileUpload.FILE_NAME_B();
        }


        public static partial class HttpError
        {
            public static UHub.CoreLib.RegExp.Compiler.Output.HttpError.ERROR_PAGE ERROR_PAGE = new UHub.CoreLib.RegExp.Compiler.Output.HttpError.ERROR_PAGE();
        }


        public static partial class HttpError
        {
            public static UHub.CoreLib.RegExp.Compiler.Output.HttpError.ERROR_PAGE_B ERROR_PAGE_B = new UHub.CoreLib.RegExp.Compiler.Output.HttpError.ERROR_PAGE_B();
        }


        public static partial class Util
        {
            public static UHub.CoreLib.RegExp.Compiler.Output.Util.STATE STATE = new UHub.CoreLib.RegExp.Compiler.Output.Util.STATE();
        }


        public static partial class Util
        {
            public static UHub.CoreLib.RegExp.Compiler.Output.Util.STATE_B STATE_B = new UHub.CoreLib.RegExp.Compiler.Output.Util.STATE_B();
        }


        public static partial class Util
        {
            public static UHub.CoreLib.RegExp.Compiler.Output.Util.CITY CITY = new UHub.CoreLib.RegExp.Compiler.Output.Util.CITY();
        }


        public static partial class Util
        {
            public static UHub.CoreLib.RegExp.Compiler.Output.Util.CITY_B CITY_B = new UHub.CoreLib.RegExp.Compiler.Output.Util.CITY_B();
        }


        public static partial class Util
        {
            public static UHub.CoreLib.RegExp.Compiler.Output.Util.ZIP ZIP = new UHub.CoreLib.RegExp.Compiler.Output.Util.ZIP();
        }


        public static partial class Util
        {
            public static UHub.CoreLib.RegExp.Compiler.Output.Util.ZIP_B ZIP_B = new UHub.CoreLib.RegExp.Compiler.Output.Util.ZIP_B();
        }



    }
}